### ISSUE TITLE
Set AllowMultiple=true for RequiredIf

### ISSUE THREAD

**Issue by jim-lightfoot** [zinofi/Umbrella#4]
Would like to be able to do this:

```
[RequiredIf("Status", Status.Closed)]
[RequiredIf("Status", Status.Resolved)]
[RequiredIf("Status", Status.Duplicate)]
public string Solution {get;set;}
```

**Comment by ricardoeduardo** [comment]
I came across this myself recently and fixed it on my dev branch. I've ported the change back into master which should allow you to do this now. Please see the following commit: https://github.com/zinofi/Umbrella/commit/531a7ee8c14f4d889aa342fa3af12ab24ffed426

I've published an updated version of the package to NuGet too: https://www.nuget.org/packages/Umbrella.DataAnnotations/
